// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Concrete;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ImagesContext))]
    partial class ImagesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Entity.Images", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImgId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Entity.ResponseImages", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("diseaseRates")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("second_top_disease")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("top_disease")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImgId");

                    b.ToTable("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
